//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmxClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kotelliada.github.io/", ConfigurationName="ServiceReference1.XXXServiceSoap")]
    public interface XXXServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем HelloWorldResult из пространства имен http://kotelliada.github.io/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://kotelliada.github.io/HelloWorld", ReplyAction="*")]
        AsmxClient.ServiceReference1.HelloWorldResponse HelloWorld(AsmxClient.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kotelliada.github.io/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync(AsmxClient.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kotelliada.github.io/Add", ReplyAction="*")]
        int Add(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kotelliada.github.io/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kotelliada.github.io/Sub", ReplyAction="*")]
        int Sub(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kotelliada.github.io/Sub", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubAsync(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kotelliada.github.io/Mul", ReplyAction="*")]
        int Mul(int x, int y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kotelliada.github.io/Mul", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MulAsync(int x, int y);
        
        // CODEGEN: Контракт генерации сообщений с именем value из пространства имен http://kotelliada.github.io/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://kotelliada.github.io/SetString", ReplyAction="*")]
        AsmxClient.ServiceReference1.SetStringResponse SetString(AsmxClient.ServiceReference1.SetStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kotelliada.github.io/SetString", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxClient.ServiceReference1.SetStringResponse> SetStringAsync(AsmxClient.ServiceReference1.SetStringRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetStringResult из пространства имен http://kotelliada.github.io/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://kotelliada.github.io/GetString", ReplyAction="*")]
        AsmxClient.ServiceReference1.GetStringResponse GetString(AsmxClient.ServiceReference1.GetStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kotelliada.github.io/GetString", ReplyAction="*")]
        System.Threading.Tasks.Task<AsmxClient.ServiceReference1.GetStringResponse> GetStringAsync(AsmxClient.ServiceReference1.GetStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kotelliada.github.io/setInt", ReplyAction="*")]
        void setInt(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kotelliada.github.io/setInt", ReplyAction="*")]
        System.Threading.Tasks.Task setIntAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kotelliada.github.io/getInt", ReplyAction="*")]
        int getInt();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kotelliada.github.io/getInt", ReplyAction="*")]
        System.Threading.Tasks.Task<int> getIntAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://kotelliada.github.io/", Order=0)]
        public AsmxClient.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(AsmxClient.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://kotelliada.github.io/", Order=0)]
        public AsmxClient.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(AsmxClient.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://kotelliada.github.io/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetString", Namespace="http://kotelliada.github.io/", Order=0)]
        public AsmxClient.ServiceReference1.SetStringRequestBody Body;
        
        public SetStringRequest() {
        }
        
        public SetStringRequest(AsmxClient.ServiceReference1.SetStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://kotelliada.github.io/")]
    public partial class SetStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string value;
        
        public SetStringRequestBody() {
        }
        
        public SetStringRequestBody(string value) {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetStringResponse", Namespace="http://kotelliada.github.io/", Order=0)]
        public AsmxClient.ServiceReference1.SetStringResponseBody Body;
        
        public SetStringResponse() {
        }
        
        public SetStringResponse(AsmxClient.ServiceReference1.SetStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetStringResponseBody {
        
        public SetStringResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetString", Namespace="http://kotelliada.github.io/", Order=0)]
        public AsmxClient.ServiceReference1.GetStringRequestBody Body;
        
        public GetStringRequest() {
        }
        
        public GetStringRequest(AsmxClient.ServiceReference1.GetStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetStringRequestBody {
        
        public GetStringRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStringResponse", Namespace="http://kotelliada.github.io/", Order=0)]
        public AsmxClient.ServiceReference1.GetStringResponseBody Body;
        
        public GetStringResponse() {
        }
        
        public GetStringResponse(AsmxClient.ServiceReference1.GetStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://kotelliada.github.io/")]
    public partial class GetStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStringResult;
        
        public GetStringResponseBody() {
        }
        
        public GetStringResponseBody(string GetStringResult) {
            this.GetStringResult = GetStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface XXXServiceSoapChannel : AsmxClient.ServiceReference1.XXXServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class XXXServiceSoapClient : System.ServiceModel.ClientBase<AsmxClient.ServiceReference1.XXXServiceSoap>, AsmxClient.ServiceReference1.XXXServiceSoap {
        
        public XXXServiceSoapClient() {
        }
        
        public XXXServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public XXXServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XXXServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public XXXServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AsmxClient.ServiceReference1.HelloWorldResponse AsmxClient.ServiceReference1.XXXServiceSoap.HelloWorld(AsmxClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            AsmxClient.ServiceReference1.HelloWorldRequest inValue = new AsmxClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new AsmxClient.ServiceReference1.HelloWorldRequestBody();
            AsmxClient.ServiceReference1.HelloWorldResponse retVal = ((AsmxClient.ServiceReference1.XXXServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxClient.ServiceReference1.HelloWorldResponse> AsmxClient.ServiceReference1.XXXServiceSoap.HelloWorldAsync(AsmxClient.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxClient.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            AsmxClient.ServiceReference1.HelloWorldRequest inValue = new AsmxClient.ServiceReference1.HelloWorldRequest();
            inValue.Body = new AsmxClient.ServiceReference1.HelloWorldRequestBody();
            return ((AsmxClient.ServiceReference1.XXXServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int x, int y) {
            return base.Channel.Add(x, y);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int x, int y) {
            return base.Channel.AddAsync(x, y);
        }
        
        public int Sub(int x, int y) {
            return base.Channel.Sub(x, y);
        }
        
        public System.Threading.Tasks.Task<int> SubAsync(int x, int y) {
            return base.Channel.SubAsync(x, y);
        }
        
        public int Mul(int x, int y) {
            return base.Channel.Mul(x, y);
        }
        
        public System.Threading.Tasks.Task<int> MulAsync(int x, int y) {
            return base.Channel.MulAsync(x, y);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AsmxClient.ServiceReference1.SetStringResponse AsmxClient.ServiceReference1.XXXServiceSoap.SetString(AsmxClient.ServiceReference1.SetStringRequest request) {
            return base.Channel.SetString(request);
        }
        
        public void SetString(string value) {
            AsmxClient.ServiceReference1.SetStringRequest inValue = new AsmxClient.ServiceReference1.SetStringRequest();
            inValue.Body = new AsmxClient.ServiceReference1.SetStringRequestBody();
            inValue.Body.value = value;
            AsmxClient.ServiceReference1.SetStringResponse retVal = ((AsmxClient.ServiceReference1.XXXServiceSoap)(this)).SetString(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxClient.ServiceReference1.SetStringResponse> AsmxClient.ServiceReference1.XXXServiceSoap.SetStringAsync(AsmxClient.ServiceReference1.SetStringRequest request) {
            return base.Channel.SetStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxClient.ServiceReference1.SetStringResponse> SetStringAsync(string value) {
            AsmxClient.ServiceReference1.SetStringRequest inValue = new AsmxClient.ServiceReference1.SetStringRequest();
            inValue.Body = new AsmxClient.ServiceReference1.SetStringRequestBody();
            inValue.Body.value = value;
            return ((AsmxClient.ServiceReference1.XXXServiceSoap)(this)).SetStringAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AsmxClient.ServiceReference1.GetStringResponse AsmxClient.ServiceReference1.XXXServiceSoap.GetString(AsmxClient.ServiceReference1.GetStringRequest request) {
            return base.Channel.GetString(request);
        }
        
        public string GetString() {
            AsmxClient.ServiceReference1.GetStringRequest inValue = new AsmxClient.ServiceReference1.GetStringRequest();
            inValue.Body = new AsmxClient.ServiceReference1.GetStringRequestBody();
            AsmxClient.ServiceReference1.GetStringResponse retVal = ((AsmxClient.ServiceReference1.XXXServiceSoap)(this)).GetString(inValue);
            return retVal.Body.GetStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AsmxClient.ServiceReference1.GetStringResponse> AsmxClient.ServiceReference1.XXXServiceSoap.GetStringAsync(AsmxClient.ServiceReference1.GetStringRequest request) {
            return base.Channel.GetStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<AsmxClient.ServiceReference1.GetStringResponse> GetStringAsync() {
            AsmxClient.ServiceReference1.GetStringRequest inValue = new AsmxClient.ServiceReference1.GetStringRequest();
            inValue.Body = new AsmxClient.ServiceReference1.GetStringRequestBody();
            return ((AsmxClient.ServiceReference1.XXXServiceSoap)(this)).GetStringAsync(inValue);
        }
        
        public void setInt(int value) {
            base.Channel.setInt(value);
        }
        
        public System.Threading.Tasks.Task setIntAsync(int value) {
            return base.Channel.setIntAsync(value);
        }
        
        public int getInt() {
            return base.Channel.getInt();
        }
        
        public System.Threading.Tasks.Task<int> getIntAsync() {
            return base.Channel.getIntAsync();
        }
    }
}
