//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab4WebFormSum.SimplexService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="A", Namespace="http://KDI/")]
    [System.SerializableAttribute()]
    public partial class A : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sField;
        
        private int kField;
        
        private float fField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string s {
            get {
                return this.sField;
            }
            set {
                if ((object.ReferenceEquals(this.sField, value) != true)) {
                    this.sField = value;
                    this.RaisePropertyChanged("s");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int k {
            get {
                return this.kField;
            }
            set {
                if ((this.kField.Equals(value) != true)) {
                    this.kField = value;
                    this.RaisePropertyChanged("k");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float f {
            get {
                return this.fField;
            }
            set {
                if ((this.fField.Equals(value) != true)) {
                    this.fField = value;
                    this.RaisePropertyChanged("f");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://KDI/", ConfigurationName="SimplexService.SimplexSoap")]
    public interface SimplexSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://KDI/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://KDI/HelloWorld", ReplyAction="*")]
        Lab4WebFormSum.SimplexService.HelloWorldResponse HelloWorld(Lab4WebFormSum.SimplexService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (AddNumbers) of message AddNumbers does not match the default value (Add)
        [System.ServiceModel.OperationContractAttribute(Action="http://KDI/AddNumbers", ReplyAction="*")]
        Lab4WebFormSum.SimplexService.AddNumbers1 Add(Lab4WebFormSum.SimplexService.AddNumbers request);
        
        // CODEGEN: Generating message contract since the wrapper name (ConcatenateStrings) of message ConcatenateStrings does not match the default value (Concat)
        [System.ServiceModel.OperationContractAttribute(Action="http://KDI/ConcatenateStrings", ReplyAction="*")]
        Lab4WebFormSum.SimplexService.ConcatenateStrings1 Concat(Lab4WebFormSum.SimplexService.ConcatenateStrings request);
        
        // CODEGEN: Generating message contract since the wrapper name (AddObjects) of message AddObjects does not match the default value (Sum)
        [System.ServiceModel.OperationContractAttribute(Action="http://KDI/AddObjects", ReplyAction="*")]
        Lab4WebFormSum.SimplexService.AddObjects1 Sum(Lab4WebFormSum.SimplexService.AddObjects request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://KDI/", Order=0)]
        public Lab4WebFormSum.SimplexService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Lab4WebFormSum.SimplexService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://KDI/", Order=0)]
        public Lab4WebFormSum.SimplexService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Lab4WebFormSum.SimplexService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://KDI/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddNumbers", WrapperNamespace="http://KDI/", IsWrapped=true)]
    public partial class AddNumbers {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KDI/", Order=0)]
        public int x;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KDI/", Order=1)]
        public int y;
        
        public AddNumbers() {
        }
        
        public AddNumbers(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddNumbersResponse", WrapperNamespace="http://KDI/", IsWrapped=true)]
    public partial class AddNumbers1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KDI/", Order=0)]
        public int AddNumbersResult;
        
        public AddNumbers1() {
        }
        
        public AddNumbers1(int AddNumbersResult) {
            this.AddNumbersResult = AddNumbersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConcatenateStrings", WrapperNamespace="http://KDI/", IsWrapped=true)]
    public partial class ConcatenateStrings {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KDI/", Order=0)]
        public string s;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KDI/", Order=1)]
        public double d;
        
        public ConcatenateStrings() {
        }
        
        public ConcatenateStrings(string s, double d) {
            this.s = s;
            this.d = d;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ConcatenateStringsResponse", WrapperNamespace="http://KDI/", IsWrapped=true)]
    public partial class ConcatenateStrings1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KDI/", Order=0)]
        public string ConcatenateStringsResult;
        
        public ConcatenateStrings1() {
        }
        
        public ConcatenateStrings1(string ConcatenateStringsResult) {
            this.ConcatenateStringsResult = ConcatenateStringsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddObjects", WrapperNamespace="http://KDI/", IsWrapped=true)]
    public partial class AddObjects {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KDI/", Order=0)]
        public Lab4WebFormSum.SimplexService.A a1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KDI/", Order=1)]
        public Lab4WebFormSum.SimplexService.A a2;
        
        public AddObjects() {
        }
        
        public AddObjects(Lab4WebFormSum.SimplexService.A a1, Lab4WebFormSum.SimplexService.A a2) {
            this.a1 = a1;
            this.a2 = a2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddObjectsResponse", WrapperNamespace="http://KDI/", IsWrapped=true)]
    public partial class AddObjects1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://KDI/", Order=0)]
        public Lab4WebFormSum.SimplexService.A AddObjectsResult;
        
        public AddObjects1() {
        }
        
        public AddObjects1(Lab4WebFormSum.SimplexService.A AddObjectsResult) {
            this.AddObjectsResult = AddObjectsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SimplexSoapChannel : Lab4WebFormSum.SimplexService.SimplexSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimplexSoapClient : System.ServiceModel.ClientBase<Lab4WebFormSum.SimplexService.SimplexSoap>, Lab4WebFormSum.SimplexService.SimplexSoap {
        
        public SimplexSoapClient() {
        }
        
        public SimplexSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimplexSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab4WebFormSum.SimplexService.HelloWorldResponse Lab4WebFormSum.SimplexService.SimplexSoap.HelloWorld(Lab4WebFormSum.SimplexService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Lab4WebFormSum.SimplexService.HelloWorldRequest inValue = new Lab4WebFormSum.SimplexService.HelloWorldRequest();
            inValue.Body = new Lab4WebFormSum.SimplexService.HelloWorldRequestBody();
            Lab4WebFormSum.SimplexService.HelloWorldResponse retVal = ((Lab4WebFormSum.SimplexService.SimplexSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab4WebFormSum.SimplexService.AddNumbers1 Lab4WebFormSum.SimplexService.SimplexSoap.Add(Lab4WebFormSum.SimplexService.AddNumbers request) {
            return base.Channel.Add(request);
        }
        
        public int Add(int x, int y) {
            Lab4WebFormSum.SimplexService.AddNumbers inValue = new Lab4WebFormSum.SimplexService.AddNumbers();
            inValue.x = x;
            inValue.y = y;
            Lab4WebFormSum.SimplexService.AddNumbers1 retVal = ((Lab4WebFormSum.SimplexService.SimplexSoap)(this)).Add(inValue);
            return retVal.AddNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab4WebFormSum.SimplexService.ConcatenateStrings1 Lab4WebFormSum.SimplexService.SimplexSoap.Concat(Lab4WebFormSum.SimplexService.ConcatenateStrings request) {
            return base.Channel.Concat(request);
        }
        
        public string Concat(string s, double d) {
            Lab4WebFormSum.SimplexService.ConcatenateStrings inValue = new Lab4WebFormSum.SimplexService.ConcatenateStrings();
            inValue.s = s;
            inValue.d = d;
            Lab4WebFormSum.SimplexService.ConcatenateStrings1 retVal = ((Lab4WebFormSum.SimplexService.SimplexSoap)(this)).Concat(inValue);
            return retVal.ConcatenateStringsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Lab4WebFormSum.SimplexService.AddObjects1 Lab4WebFormSum.SimplexService.SimplexSoap.Sum(Lab4WebFormSum.SimplexService.AddObjects request) {
            return base.Channel.Sum(request);
        }
        
        public Lab4WebFormSum.SimplexService.A Sum(Lab4WebFormSum.SimplexService.A a1, Lab4WebFormSum.SimplexService.A a2) {
            Lab4WebFormSum.SimplexService.AddObjects inValue = new Lab4WebFormSum.SimplexService.AddObjects();
            inValue.a1 = a1;
            inValue.a2 = a2;
            Lab4WebFormSum.SimplexService.AddObjects1 retVal = ((Lab4WebFormSum.SimplexService.SimplexSoap)(this)).Sum(inValue);
            return retVal.AddObjectsResult;
        }
    }
}
